rsync:
    user: root
    server: myserver.org
    args: -avze 'ssh -i /root/somekey.pem' --exclude tmp/ --exclude temp/ --exclude cache/
    log_file: /var/log/pybackup.log
    backup_dir: /backup/

dirs:
    - /var/www/
    - /var/vmail/
    - /root/

mysql:
    user: root
    server: myserver.org
    backup_dir: /mysql/
    password: mysql_pass

databases:
    - vexim
    - wordpress
    - joomla
